name: Pruebas Unitarias

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout de las pruebas unitarias del código
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
      node-version: 18


    - name: intalar Node.js
      run: npm install
      

     - name: ejecutar Node.js
      run: npm test