name: Pruebas Unitarias y Bloqueo de Push

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del código
      uses: actions/checkout@v2

    - name: Configurar el entorno
      run: |
        # Instala las dependencias de tus pruebas, esto puede variar según tu proyecto.
        # Por ejemplo, en Java puedes usar 'mvn install' o 'gradle build'.
        # En Python puedes usar 'pip install -r requirements.txt'.
        # Asegúrate de usar los comandos específicos de tu proyecto aquí.
        echo "Configurando entorno..."
        # Ejecuta tus pruebas unitarias.
        # Por ejemplo, en Java podrías usar 'mvn test', en Python 'pytest', etc.
        echo "Ejecutando pruebas unitarias..."
        # Agrega comandos específicos para ejecutar tus pruebas aquí.
        # Si las pruebas fallan, el flujo se detendrá y el push será bloqueado.

    - name: Bloquear el push si las pruebas fallan
      if: failure()
      run: echo "Las pruebas unitarias fallaron. No se puede hacer push."
